select CURRENCY, RATE, DATE, WEEKDAY(DATE) AS ID_DAYWEEK, DAYNAME(DATE) AS WEEKDAY
 from CURRENCY_RATES
 where DATE = (select MAX(DATE) FROM CURRENCY_RATES)
	and DAYNAME(DATE) != "Saturday" or "Sunday";