select R.CURRENCY, RATE, DATE, DAYNAME(DATE) AS WEEKDAY
FROM CURRENCY_RATES R inner JOIN CURRENCY C
ON R.CURRENCY = C.CURRENCY
 where DATE = (select MAX(DATE) FROM CURRENCY_RATES)
	and DAYNAME(DATE) != "Saturday" or "Sunday";
