SELECT X.ID , X.CURRENCY, X.RATE, X.DATE  FROM CURRENCY C inner JOIN 
(
SELECT X.ID , X.CURRENCY, X.RATE, X.DATE, RANK() OVER(PARTITION BY X.CURRENCY ORDER BY X.DATE desc) num
FROM CURRENCY_RATES X
) X 
ON X.CURRENCY = C.CURRENCY 
WHERE num <= 2
order by X.DATE 
