select CURRENCY, count(CURRENCY) sum
from CURRENCY
group by CURRENCY
having count(CURRENCY) >1;

DELETE A.* FROM CURRENCY A,
(SELECT
B.CURRENCY, B.DESCRIPTION, MIN(B.id) mid
FROM CURRENCY B
GROUP BY B.CURRENCY ) C
WHERE A.CURRENCY = C.CURRENCY AND A.id > C.mid 
